### ISSUE TITLE
Admin Login page blank after following "Getting Started" instructions

### ISSUE THREAD

**Issue by zangai** [sulu/sulu-minimal#108]
After following the instructions in the Getting Started section of the documentation, I try to navigato towards the admin section (http://localhost/admin). It gets redirection towards /admin/login, and I am presented with a (seemingly) blank page. The page source does provide a few HTML tags, but nothing is being displayed.

Did I miss the installation of some frontend framework or something?

**Comment by alexander-schranz** [comment]
@zangai can you check the network log of your browser?

**Comment by zangai** [comment]
@alexander-schranz Certainly, I have a screenshot, and a dumped file (.har) that Microsoft Edge let me export as. As you can see it seems to give a 404 for the translation json file, but I didn't think it would have anything to do with it. I also don't know how I would generate this file if it is required.

![image](https://user-images.githubusercontent.com/1556962/44045431-c0d920ac-9f28-11e8-8941-71e1c540cafe.png)


[suluadmin_edge.zip](https://github.com/sulu/sulu-minimal/files/2283885/suluadmin_edge.zip)

**Comment by alexander-schranz** [comment]
@zangai looks for me `composer install` did fail. Can you try to rerun `composer install`? Also make sure you check `Disable cache` in your dev tools else it will still load errors `(from cache)`

**Comment by zangai** [comment]
Upon execution of `composer install` I found that the process was being terminated because of a timout. I am running on a docker instance, and it isn't very fast at times. After increasing the timeout value it managed to get further than the clearCache script.
At first it gave me a message about not being able to remove the AdminBundle (husky) directory prior to reinstalling. I have to remove the directory on my host side with docker turned off to be able to remove it properly.
After removing the directory, and once again running `composer install`, it went through and everything seems to have been installed properly now.

Thanks for the help @alexander-schranz :)
