### ISSUE TITLE
.env file not found at composer create project

### ISSUE THREAD

**Issue by mario-fehr** [sulu/sulu-minimal#118]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0.0-alpha4

#### Actual Behavior

When you run composer create project, you get an error that the .env file was not found.

#### Expected Behavior

The normal behavior should be that the `.env.dist` should be copied to `.env`.

#### Steps to Reproduce

Run `composer create-project sulu/sulu-minimal:2.0.0-alpha4`

**Comment by danrot** [comment]
fixed in #119
