### ISSUE TITLE
Memory error when installing `sulu-minimal` via Composer

### ISSUE THREAD

**Issue by nickreynke** [sulu/sulu-minimal#127]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.22 of `sulu-minimal`
| Browser Version | Console

#### Actual Behavior

When installing `sulu-minimal` over the console via Composer I get a memory error:

```
Installing sulu/sulu-minimal (1.6.22)
  - Installing sulu/sulu-minimal (1.6.22): Loading from cache
Created project in sulutest
Loading composer repositories with package information
Updating dependencies (including require-dev)
PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 67108864 bytes) in phar:///usr/lib/plesk-9.0/composer.phar/src/Composer/DependencyResolver/Solver.php on line 220

Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 67108864 bytes) in phar:///usr/lib/plesk-9.0/composer.phar/src/Composer/DependencyResolver/Solver.php on line 220

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.
```

#### Expected Behavior

Should install correctly and without a memory leak.

#### Steps to Reproduce

* Debian 8.11
* Plesk Onyx 17.8.11 Update Nr. 27
* PHP version: `7.2.11` (CLI)
* Composer version: `1.7.2`

Also reproduced on local machine:

* macOS 10.12.6
* PHP version: `7.2.7` (CLI)
* Composer version: `1.7.2`

#### Possible Solutions

Editing the locally stored `php.ini` of the corresponding PHP version, but Composer installation shouldn't run into a memory problem.

**Comment by alexander-schranz** [comment]
Hello @nickreynke,

this is no error of sulu please have a look at composer [troubleshooting](https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors) else you think composer have an error provide a issue [there](github.com/composer/composer).

**Comment by nickreynke** [comment]
Okay, running PHP with `-d memory_limit=-1` did the job. Thank you!
