### ISSUE TITLE
Memory error when installing `sulu-minimal` via Composer

### ISSUE THREAD

**Issue by JOduMonT** [sulu/sulu-minimal#129]
even after trying this [trick](https://github.com/sulu/sulu-minimal/issues/127)

\# php -dmemory_limit=-1 $HOME/bin/composer.phar create-project sulu/sulu-minimal . -n
Installing sulu/sulu-minimal (1.6.22)
  - Installing sulu/sulu-minimal (1.6.22): Loading from cache
Created project in .
Loading composer repositories with package information
Updating dependencies (including require-dev)

mmap() failed: [12] Cannot allocate memory
mmap() failed: [12] Cannot allocate memory

Fatal error: Out of memory (allocated 779100160) (tried to allocate 75497472 bytes) in phar:///home/jodumont/bin/composer.phar/src/Composer/DependencyResolver/RuleSet.php on line 90

so what else I could try ?

**Comment by alexander-schranz** [comment]
Hello @jodumont,
is it possible that you have only 750mb ram available on your system?

**Comment by JOduMonT** [comment]
@alexander-schranz sorry I omit few detail
it's a VPS, and yes the 750mb seams a hard limit

**Comment by alexander-schranz** [comment]
@jodumont maybe you find some help in the composer https://github.com/composer/composer/issues.
Performance improvements can be make when you have unzip installed in your OS also make sure you have the newest version of composer by running `php $HOME/bin/composer.phar self-update`.

Else I would try to create the project on a machine which has more memory. Then deploy the project to your VPS with the composer.lock file which was created after the create project where you then run just composer install which should not need so much memory as it don't need to resolve the dependencies.

**Comment by JOduMonT** [comment]
thank @alexander-schranz; I'll try the composer.lock alternative
