### ISSUE TITLE
Commands not executable after running composer create-project

### ISSUE THREAD

**Issue by gisostallenberg** [sulu/sulu-minimal#14]
After running composer create-project the commands in bin/ are not executable.

Also see https://github.com/composer/composer/issues/5622

**Comment by wachterjohannes** [comment]
@gisostallenberg can we do something about that? it seems that also composer closes the issue because there is no way to fix it?

**Comment by gisostallenberg** [comment]
@wachterjohannes at least the documentation should tell you to run `chmod +x`.

**Comment by gisostallenberg** [comment]
Closing this issue, see https://github.com/sulu/sulu-docs/issues/265
