### ISSUE TITLE
admin-bundle javascript hooks advice

### ISSUE THREAD

**Issue by greenlevel** [sulu/sulu-minimal#147]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | latest sulu-minimal
| Browser Version | Browser name and version

I am new to sulu and symfony.

I am interest in using this cms. But was wondering how to edit certain admin features.
Like i don't want the preview sidebar.

When looking at the cookbook.

```
layout: {
    extendExisting: false,
    navigation: {
        collapsed: false,
        hidden: false
    },
    content: {
        width: 'fixed',
        leftSpace: true,
        rightSpace: true,
        topSpace: true
    },
    sidebar: false
}
```

" just needs to be placed in the return block of the javascript-component and the AdminBundle does the rest"

Where do you place this? in the sulu-content.js file?
and how? I tried below but that isn't working. 

```
`handleLayoutMarker = function(layout) {

return layout {
            navigation: {
                collapsed: false,
                hidden: false
            },
            content: {
                width: 'fixed',
                leftSpace: true,
                rightSpace: true,
                topSpace: true
            },
            sidebar: false
             };
```
`
Need some help to get started.Thanks in advance

**Comment by alexander-schranz** [comment]
Hello @greenlevel,

If you want to use the whole space I think its only:

```js
        layout: {
            content: {
                width: 'max'
            }
        },
```

or if you want without a sidebar but some space the layout should be:

```js
        layout: {
            content: {
                width: 'fixed',
                leftSpace: true,
                rightSpace: true
            }
        },
```

**Comment by alexander-schranz** [comment]
@greenlevel But thats only when you create a custom bundle. If you just want to disable the preview in the content area you need to configure it in the your configuration:

```yaml
sulu_preview:
    mode: off
```

You never change files inside `vendor` folder when working with composer based projects.

**Comment by greenlevel** [comment]
@alexander-schranz 

Thanks for the feedback.

I placed your sulu_preview in the app/config/admin/config.yml
but that doesn't work. Where do i need to place it? 

```
# SuluAdmin Configuration
sulu_admin:
    name: "%sulu_admin.name%"
    email: "%sulu_admin.email%"
    
sulu_preview:
    mode: off

```

**Comment by alexander-schranz** [comment]
@greenlevel did you clear the symfony cache?

**Comment by greenlevel** [comment]
Thanks that did the trick !

I noticed that when having the preview removed there is a lot of space on the rigfht side. Maybe it's better that the main content fills up the space better?
 
I would also like to have the admin navigation not collapsed but open.
Is that also a setting you can add in the config file?

Thanks!

**Comment by alexander-schranz** [comment]
@greenlevel
I would be too wide on big screens thats why only a certain space is used.
we are working on the 2.0 release currently there you can make the navigation to stay open everytime.
