### ISSUE TITLE
Routing seems to be messed up right out of the box

### ISSUE THREAD

**Issue by mareksuscak** [sulu/sulu-minimal#161]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.24
| Browser Version | Chrome 72.0.3626.119

#### Actual Behavior

Upon creating new project, homepage routing seems to be messed up. It keeps redirecting to `/en` and failing to load the homepage completely. The preview in admin works though.

#### Expected Behavior

I would expect the example homepage to work right out of the box.

#### Steps to Reproduce

1. Follow [the setup steps](https://github.com/sulu/sulu-docker).
2. Visit sulu.localhost:10080

![image](https://user-images.githubusercontent.com/613647/53538337-8bf1bd00-3b0d-11e9-812b-1fca755effc3.png)

**Comment by niklasnatter** [comment]
Hey,
unfortunately i am not able to reproduce that issue. During my test, no redirect to `/en` happens. Is it possible that your browser cached this redirect?

**Comment by mareksuscak** [comment]
It's likely because I was running another instance of Sulu on the same URL before and that one had a 301 redirect set up it seems. I was kind of assuming that it's not being respected when I disabled the cache but from what I'm reading around the internet, these redirects have a separate cache that must be cleaned up through `chrome://net-internals`. Will test and let you know.

**Comment by mareksuscak** [comment]
I can confirm that the redirect was cached so this was a false positive. Closing this ticket out as it's a non-issue.
