### ISSUE TITLE
Not able to search for media, contacts, .. in general search

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu-minimal#20]
It should be possible to search for contacts, medias like in sulu-standard.

![bildschirmfoto 2016-09-05 um 18 41 25](https://cloud.githubusercontent.com/assets/1698337/18253848/6a7e63ba-7398-11e6-93d3-77450093627e.png)

**Comment by danrot** [comment]
That was already fixed some time ago. However, the index will not be created before there is any entry in it. So you have to create a contact before the contacts will be listed in that dropdown.
