### ISSUE TITLE
Content tree nodes empty

### ISSUE THREAD

**Issue by rflorent** [sulu/sulu-minimal#24]
Hello,

content tree nodes are not displayed anymore in admin side.
I can still create content nodes, but the tree is empty.

I check ajax call :

`http://www.mydomainname.com/admin/api/nodes/9b16b955-f26f-4abc-9c36-3858c6872d45?webspace=mydomainname&language=fr&fields=title,order,published&exclude-ghosts=false&exclude-shadows=false&&tree=true

{"_embedded":{"nodes":[]}}`

If I disable option tree, I got the node in data return 

`http://www.mydomainname.com/admin/api/nodes/9b16b955-f26f-4abc-9c36-3858c6872d45?webspace=mydomainname&language=fr&fields=title,order,published&exclude-ghosts=false&exclude-shadows=false&&tree=false

{"id":"9b16b955-f26f-4abc-9c36-3858c6872d45","path":"\/cmf\/mydomainname\/contents\/fsdgfdg","hasChildren":false,"concreteLanguages":["fr"],"_links":{"children":{"href":"\/admin\/api\/nodes?parent=9b16b955-f26f-4abc-9c36-3858c6872d45&language=fr&fields=title%2Corder%2Cpublished"}},"_embedded":{"nodes":[]},"title":"fsdgfdg","order":20,"published":"2016-09-29T12:16:15.000+02:00","publishedState":true,"_permissions":{"view":false,"add":false,"edit":false,"delete":false,"archive":false,"live":false,"security":false}}`

I think this is a bug and I don't know what to do.

I use minimal edition with theme bundle, sulu core 1.3. 

Thanks

Thansks

**Comment by rflorent** [comment]
off course, I clear cache with website, admin, console in dev and prod mode.

**Comment by rflorent** [comment]
webspace key contain "-", I rewrite key without "-" and change in database.
Content node tree is back...

**Comment by danrot** [comment]
That's a known issue: https://github.com/sulu/sulu/issues/2882
