### ISSUE TITLE
Automate tagging a release

### ISSUE THREAD

**Issue by gisostallenberg** [sulu/sulu-minimal#27]
As can be read on https://getcomposer.org/doc/04-schema.md#version:

> The version of the package. In most cases this is not required and should be omitted (see below).
> [...]
> Optional if the package repository can infer the version from somewhere, such as the VCS tag name in the VCS repository. In that case it is also recommended to omit it.

and

> Note: Packagist uses VCS repositories, so the statement above is very much true for Packagist as well. Specifying the version yourself will most likely end up creating problems at some point due to human error.
#26 shows this human error.

**Comment by gisostallenberg** [comment]
![image](https://cloud.githubusercontent.com/assets/11526270/19232161/908ecfde-8ede-11e6-980b-192514b72659.png)

I understand it is needed for the version in Admin. Then tagging a release should be automated, so this error can not happen. I'm willing to create some functionality for this.

**Comment by danrot** [comment]
Yeah, that's a real issue... How would you imagine the automation for this? It's a bit complicated, since it should already be written correctly when commiting. Also, when run in production you usually don't have a git repository to infer the version number.

**Comment by alexander-schranz** [comment]
as we removed the `version` from the composer.json this is not longer an issue.
