### ISSUE TITLE
Remove ffmpeg configuration from `app/config/config`

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu-minimal#3]
This would be quite easy if the library would use the symfony/process component to find the executable. I have created an issue there. As long as it is not fixed there we should keep the configuration https://github.com/pulse00/ffmpeg-bundle/issues/13

**Comment by zinzinday** [comment]
Set permission as programming
`chmod +x /path/to/ffmpeg`

**Comment by alexander-schranz** [comment]
we should close this issue after we updated the docs for 2.0: https://github.com/sulu/sulu-docs/blob/develop/cookbook/video-preview-images.rst
