### ISSUE TITLE
console sulu:translate:export

### ISSUE THREAD

**Issue by jcena14** [sulu/sulu-minimal#35]
**UPD: OK, I found the reason behind that strange behavior:**
I run the console command from the bin directory, not from the root directory. So the script created the `web/admin/translations` inside the bin directory itself (I didn't notice that in time, my bad). Probably output should be prefixed by something like `__DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR` (and checked for other scripts).

**Original question:**
I can't create my custom translation. I'm new to this, so probably I'm doing something wrong. This is how I acted;
I copy-pasted the `backend.en.xlf` from
`/vendor/sulu/sulu/src/Sulu/Bundle/AdminBundle/Resources/translations/sulu`
to
`/app/Resources/translations/sulu`
renamed it to `backend.ru.xlf` and changed inside the `source-language` property from "en" to "ru".
Next, I added to `/app/Resources/config.yml` the following lines:

```
sulu_core:
  ...
  locales:
    en: English
    ru: Russian
  translations:
    - en
    - ru
```
Next, I run the `bin/console sulu:translate:export ru` with the following output:

> Exported 856 translations to web/admin/translations for locale ru

but despite to that saying there is no `sulu.ru.json` in `/web/admin/translations` and (of course) sulu admin stop working when I change it to "ru". So, what am I doing wrong?

P.S.
I'm sorry if this is the wrong place to ask such questions. If so, please point me to the right place to discuss them.

**Comment by danrot** [comment]
@jcena14 I think there are also other symfony commands not working when being called this way, and it is not officially documented that way. So I am closing this issue, I hope that this is ok.

**Comment by jcena14** [comment]
@danrot Of course you can leave it as it is, but I think I've found a very easy fix:
just add the `chdir(__DIR__);` to the top of the `console.php`.

This shouldn't affect the user working directory (at least in my test it didn't), but all further relative paths will be based on the `console.php` directory instead of the directory from which the console command was called. Otherwise it's pretty strange to ask a user to cd to the project root directory before calling the `console` or `adminconsole` commands. What do you think?

**Comment by danrot** [comment]
@jcena14 I'd like to stay as close as possible to the symfony edition. This is quite an essential change, which might have unpredictable consequences...
