### ISSUE TITLE
MIME type of OGV video detected as application/ogg

### ISSUE THREAD

**Issue by yarbala** [sulu/sulu-minimal#47]
Sulu minimal edition (version 1.5.4) recognizes MIME type of *.ogv files as application/ogg, but type of such files should be video/ogv

**Comment by alexander-schranz** [comment]
@yarbala mime type detection is not done by sulu itself. Please check if you installed the `php_fileinfo` module. And I remember there was a problem that apache need also be configured correctly that the extension is mapped to the correct mimetype. 

I did use the following example and it did work correctly on my machine (nginx, php7, php fileinfo module installed): https://commons.wikimedia.org/wiki/File:Typing_example.ogv

**Comment by alexander-schranz** [comment]
closed as no more information where given to reproduce.
