### ISSUE TITLE
Cannot add new media folder - forbidden due to permissions

### ISSUE THREAD

**Issue by forsetius** [sulu/sulu-minimal#52]
Hello,
I'm trying the `sulu-minimal` package and all is going well, except for media. I can't add any media folder and (supposedly) uploaded images are not listed. When creating media folder there is an error message: "Operation forbidden The available permissions are not sufficient for this operation". When uploading there is no error, to the contrary - there is a thumbnail and success message but afterwards there is no entry on the media list, just circles pulsing.

At first I ensured that all the Sulu project directory has user:www-data 777 permissions. Then I checked and default admin has role User. I added "pl" localization but admin has permissions for both "en" and "pl". Also, User role has all the permissions on.

In the webspace XML file I have:
```xml
[...]
    <localizations>
        <localization language="en"/>
        <localization language="pl" default="true"/>
    </localizations>
[...]
    <portals>
        <portal>
            <name>example.com</name>
            <key>example</key>

            <environments>
                <environment type="prod">
                    <urls>
                        <url language="pl">{host}</url>
                        <url language="en">{host}/en</url>
                    </urls>
                </environment>
[...]
```

Is it some bug or is it something on my side?

**Comment by alexander-schranz** [comment]
@forsetius sorry that there was no answer. I hope you could solve it. Else I think you need to check which locale was send as query parameter to the upload request. Will close this issue for inactivity else let us know if we can help. Also feel free to contact us in our slack channel: https://sulu.io/en#questions
