### ISSUE TITLE
ProxyManager FileNotWritableException 

### ISSUE THREAD

**Issue by CharlesMure** [sulu/sulu-minimal#56]
I follow the Getting Started guide to install the sulu-minimal. Everything went well until I try to add a new page. The page was created but I couldn't access to it. It throws me an exception when I'm trying to access to it:

FileNotWritableException  in vendor/ocramius/proxy-manager/src/ProxyManager/GeneratorStrategy/FileWriterGeneratorStrategy.php (line 98)

Could not write to path "/home/my-project/var/cache/website/dev/sulu/proxies/ProxyManagerGeneratedProxy__PM__SuluBundleContentBundleDocumentHomeDocumentGeneratedfab3c42b03aa8246cf7ce59722a4c211.php.59875689ac1952.50755017": path does not exist

I tried to create this file manually (from a terminal) and it said the filename was to long for the system (I'm running on Ubuntu 16).
So inside the file FileWriterGeneratorStrategy.php, I change uniqid('', true) to uniqid('', false) to reduce the length.
With this simple hack, everything went well !

However, is there a cleaner solution for it ?

Thanks !

**Comment by wachterjohannes** [comment]
@CharlesMure do you use an encrypted directory for your cache? there the limit seems to be 143 characters. I think this should be an issue in the package `ocramius/proxy-manager`.

**Comment by CharlesMure** [comment]
I didn't thought about it at first but my home directory was encrypted by default by Ubuntu. So I move the whole project outside of my personal directory and now it works well ! 
Thanks !
