### ISSUE TITLE
Parse error: syntax error, unexpected ':', expecting ';' 

### ISSUE THREAD

**Issue by jschouwstra** [sulu/sulu-minimal#69]
I get this error on installing sulu minimal version with composer:

( ! ) Parse error: syntax error, unexpected ':', expecting ';' or '{' in C:\wamp64\www\project-name\vendor\ocramius\proxy-manager\src\ProxyManager\Configuration.php on line 97
--

**Comment by forsetius** [comment]
I've got something similar. It turned out that this bundle uses PHP7 syntax so I had to upgrade PHP on server.

Edit: I checked and it turns out I'm right - ocramius\proxy-manager requires PHP 7.0 from version 2.0.0 (2016-01-30) and from version 2.1.0 (2016-11-30) it requires PHP 7.1. In `composer.json` there is:
```json
"require": {
    "php": "^7.1.0"
}
```

**Comment by forsetius** [comment]
Checked further and `sulu/document-manager` requires 
```json
"ocramius/proxy-manager": "~1.0 | ~2.0"
```
I suspect it should be: 
```json
"ocramius/proxy-manager": "~1.0 || ~2.0"
```

**Comment by alexander-schranz** [comment]
@forsetius @jschouwstra sulu is compatible with PHP 5.5 only the current develop uses PHP7 syntax.
Please check if your PHP CLI Version is the same as your Webserver PHP version else if you can't use the same version set the version of the webservers php version in composer.json platform flag (https://getcomposer.org/doc/06-config.md#platform) and run `composer update` again.

**Comment by jschouwstra** [comment]
@forsetius @alexander-schranz   I've upgraded to PHP 7, now I get the error in the CLI:

Fatal error: Cannot use $this as parameter in C:\wamp64\www\sulu-demo\var\cache\admin\dev\adminDevDebugProjectContainer.php on line 14041

And in the browser the same error as described in this issue.

Also there's not even a ocramius/proxy-manager package in my composer.json, should I add it?

**Comment by alexander-schranz** [comment]
there was a error to this time with ocramius proxy manager with the supported php version this was fixed a short time after the this issue was created.
