### ISSUE TITLE
add Docker container for dev environment 

### ISSUE THREAD

**Issue by foued611** [sulu/sulu-minimal#72]
Goal:
Consistent development environments for entire Comunity. All developers use the same OS, same system libraries, same language runtime, no matter what host OS they are using (even Windows if you can believe it).

**Comment by alexander-schranz** [comment]
Not sure if we will everadd a docker env to this repository but there is an unoffical docker image maintained by @wachterjohannes and @TomKeur here: https://github.com/wachterjohannes/sulu-docker

**Comment by niklasnatter** [comment]
We actually moved the `sulu-docker` repository into the sulu namespace this week. The repository is now accessible on https://github.com/sulu/sulu-docker 🙂

**Comment by wachterjohannes** [comment]
@foued611 finally the repo was moved to the official namespace so i think we can close this
