### ISSUE TITLE
Separate xml templates for each workspace

### ISSUE THREAD

**Issue by gnsimoes** [sulu/sulu-minimal#74]
Hi,

Is it possible to have different set of xml templates for each webspace?
Only those templates should be accessible in the webspace context. We would like to configure different xml templates, because we will have different layouts and website purposes. 

Thanks,

**Comment by alexander-schranz** [comment]
@gnsimoes this can be done by using the [theme bundle](http://docs.sulu.io/en/latest/book/themes.html) as if the `view` template can't be found in the default folder or the theme folder the template will not be shown in the backend dropdown.

You need to add the theme bundle to your composer requirements `composer require sulu/theme-bundle`

As documented add the bundles to the AbstractKernel:

```php
            new Sulu\Bundle\ThemeBundle\SuluThemeBundle(),
            new Liip\ThemeBundle\LiipThemeBundle(),
```


Add `theme` property to both webspaces.xml file after `localization`:

```xml
<theme>webspace1</theme>
```

```xml
<theme>webspace2</theme>
```

Configure the available themes in `app/config/config.yml`

```yml
liip_theme:
    themes: ["webspace1", "webspace2"]
    active_theme: "webspace1"
    load_controllers: false
```

Now if a template should only be available in `webspace2` create the html.twig file of that template only in the theme folder: `app/Resources/themes/webspace2/templates/example.html.twig`.

**Comment by gnsimoes** [comment]
Hi @alexander-schranz , thanks for your response,

Our question is not about the theming, that we have it well configured with Sulu documentation.
We want to know if it is possible to have in the administration interface, a set of page templates for webspace1 and another set of page templates for webspace2.
At the moment when you create a page, you have available all the templates created on folder app/Resources/templates/pages/*.xml.

**Comment by alexander-schranz** [comment]
@gnsimoes I did understand you correctly. The theme bundle is the solution for your problem.

Example we add a template `app/Resources/templates/pages/example.xml` which is configured as view this way: `<view>templates/example</view>` sulu will search for the view in `app/Resources/views/templates/example.html.twig`. As we don't want that this template is available in all themes you only create `example.html.twig` in the theme you want it to be shown e.g. `app/Resources/themes/webspace2/templates/`.

Now Webspace 1 show:

![bildschirmfoto 2017-11-13 um 18 22 36](https://user-images.githubusercontent.com/1698337/32739331-ccc832e6-c89f-11e7-89e9-abf6fc32a01a.png)

And Webspace 2 shows also the new added template as this is only available in that theme:

![bildschirmfoto 2017-11-13 um 18 23 16](https://user-images.githubusercontent.com/1698337/32739339-d25ddde6-c89f-11e7-8676-c954184d60d2.png)

**Comment by gnsimoes** [comment]
Ok, know I understand with your explanation :) thanks!
I will try on our project and let you know if we could resolve it.

**Comment by gnsimoes** [comment]
Hi @alexander-schranz , it works!
Thanks for your help!
