### ISSUE TITLE
Teaser missing data after clear indexes folder

### ISSUE THREAD

**Issue by gnsimoes** [sulu/sulu-minimal#75]
Hello,

When we clear the content of var/indexes, we lost the data in the teaser content type. When it happens, we have to save those contents configured as a teaser, to rebuild the index data.
There is any way to rebuild its indexes, without having to go through all the content?

Thanks,

**Comment by alexander-schranz** [comment]
@gnsimoes you can reindex admin searchindex and website searchindex with the following commands:

```bash
bin/console massive:search:reindex
bin/websiteconsole massive:search:reindex
```

**Comment by gnsimoes** [comment]
I @alexander-schranz ,

It did work, thanks for your help.
