### ISSUE TITLE
Sulu CMS 1.6 `Search indexes “page_example_published” not known.` error (1.5 works)

### ISSUE THREAD

**Issue by mykbas** [sulu/sulu-minimal#93]
Hello, I've faced strange behavior of sulu-minimal project, I am installing sulu-minimal 1.5 - indexing of massive_page_example_published-en-i18n and search field on client homepage works as expected, sulu-minimal 1.6 gives an error `Search indexes "page_example_published" not known. Known indexes: "page", "contact"` and only massive_contact and massive_page-en-i18n indexes are created.

P.S. tried purging and rebuilding indexing with no errors, cleared cache, installed barebone repo from scratch both locally (PHP7.2) and on docker containers (PHP7.1)... now I just got stuck

Example projects I have also tested:

- Sulu 1.6 that gives the same error https://github.com/wachterjohannes/sulu-docker
- Sulu 1.3 with working index https://github.com/sulu/sulu-workshop-websc16
- Sulu 1.5 with working index https://github.com/alexander-schranz/example-sulu-website

**Comment by mykbas** [comment]
do not know why but after some time publishing posts on 1.6 project the index for 'page_example_published' appeared, but I think the default to see `zero found` as in v.1.5 would be better for newly created applications.

**Comment by mykbas** [comment]
and `bin/console massive:search:index:rebuild` doesn't create `page_example_published` however there are published pages in database, this index folder is somehow created on publishing new data...

**Comment by alexander-schranz** [comment]
@mykbas bin/console (bin/adminconsole) will only create indexes of the admin for the website you need call `bin/websiteconsole`

**Comment by mykbas** [comment]
@alexander-schranz I've just tried removing indexes folders and running with `bin/websiteconsole massive:search:index:rebuild` on barebone sulu-minimal v1.6 - only `massive_contact` and `massive_page-en-i18n` created and same error `Search indexes "page_example_published" not known.` for search on homepage.

**Comment by alexander-schranz** [comment]
@mykbas I'm not able to reproduce it. Can you check it for a new project by running the following commands:

```bash
composer create-project sulu/sulu-minimal my-project
cd new-project
bin/adminconsole sulu:build dev

# now you should see a list of indexes
ls var/indexes/ 

bin/adminconsole massive:search:purge --all --force
# now no indexes should be listed
ls var/indexes/ 

bin/adminconsole massive:search:reindex
# now the following indexes should be listed
#  - massive_category-en-i18n               
#  - massive_page_example-en-i18n
#  - massive_contact
#  - massive_media-en-i18n           
#  - massive_snippet-en-i18n
#  - massive_page-en-i18n
ls var/indexes/ 

bin/websiteconsole massive:search:reindex
# now also the published index is listed there:
#  - massive_page_example_published-en-i18n
ls var/indexes/ 
```

**Comment by mykbas** [comment]
@alexander-schranz for comparison I just tried on the same environment PHP7.0 v1.6 and 1.5 (previously tried also v1.3 - indexes worked as in 1.5) with output below:

Sulu CMS 1.6
```bash
composer create-project sulu/sulu-minimal project
cd project
# var/indexes - nothing there

bin/adminconsole sulu:build dev

# now you should see a list of indexes
ls var/indexes/ 
# - massive_contact
# - massive_page-en-i18n

bin/adminconsole massive:search:purge --all --force
# now no indexes should be listed
ls var/indexes/ 
# var/indexes - nothing there

bin/adminconsole massive:search:reindex
ls var/indexes/ 
# - massive_contact
# - massive_page-en-i18n

bin/websiteconsole massive:search:reindex
ls var/indexes/
# - massive_contact
# - massive_page-en-i18n
```

Sulu CMS 1.5
```bash
composer create-project sulu/sulu-minimal project 1.5
cd project
# var/indexes - nothing there

bin/adminconsole sulu:build dev

# now you should see a list of indexes
ls var/indexes/ 
# - massive_contact
# - massive_page_example-en-i18n
# - massive_page_example_published-en-i18n

bin/adminconsole massive:search:purge --all --force
# now no indexes should be listed
ls var/indexes/ 
# var/indexes - nothing there

bin/adminconsole massive:search:reindex
ls var/indexes/ 
# - massive_contact
# - massive_page_example-en-i18n

bin/websiteconsole massive:search:reindex
ls var/indexes/
# - massive_contact
# - massive_page_example-en-i18n
# - massive_page_example_published-en-i18n
```

**Comment by alexander-schranz** [comment]
@mykbas does this only happens when you have no pages? or when you create a new page in the tree and purge and reindex the published does also exist in 1.6?

**Comment by mykbas** [comment]
@alexander-schranz it happens with no pages. When I create new page via admin panel `published` index folder appears, but after purging and reindexing (also with bin/websiteconsole) `published` is missing again for v1.6. Next time index is created after continuing adding new pages via admin panel.

**Comment by alexander-schranz** [comment]
@mykbas how did you purge and reindex? What is the output of reindexing command.

**Comment by mykbas** [comment]
@alexander-schranz Thanks for your patience and pointing out the right direction. Probably I messed smth up with consoles or maybe there were leftovers in docker containers, I was reproducing the whole workflow from scratch and it seems to be working now:

1. Creating a new project `sulu/sulu-minimal (1.6.16)`
```
composer create-project sulu/sulu-minimal project
cd project
bin/adminconsole sulu:build dev
ls var/indexes/
# - massive_contact 
# - massive_page-en-i18n
```

2. Add a new simple page via content in admin panel.
```
ls var/indexes/
# - massive_contact  
# - massive_page-en-i18n  
# - massive_page_example-en-i18n  
# - massive_page_example_published-en-i18n
```

3.  Purge, reindex and check:
```
bin/adminconsole massive:search:purge --all --force
ls var/indexes/
# empty

bin/adminconsole massive:search:reindex
ls var/indexes/
# - massive_contact  
# - massive_page-en-i18n  
# - massive_page_example-en-i18n  
bin/websiteconsole massive:search:reindex
ls var/indexes/
# - massive_contact  
# - massive_page-en-i18n  
# - massive_page_example-en-i18n  
# - massive_page_example_published-en-i18n
```

**Comment by mareksuscak** [comment]
This is definitely not fixed. Just set up a new sulu instance through sulu-docker and encountered the same problem., the steps above did not help.
